/**
 * Generated-file headers (docs/19-target-mappings.md, "Generated output
 * layout"). TypeScript uses `//` line comments, same as Swift and Kotlin.
 */

export function moduleHeader(compilerVersion: string, sourceFile: string, moduleName: string): string[] {
  return [
    `// Generated by ClearKrypt ${compilerVersion} from ${sourceFile} (module ${moduleName}).`,
    '// Do not edit. Changes will be overwritten.',
  ];
}

export function supportHeader(compilerVersion: string): string[] {
  return [
    `// Generated by ClearKrypt ${compilerVersion}. Shared support definitions.`,
    '// Do not edit. Changes will be overwritten.',
  ];
}
