import IDECore
import SwiftUI

struct ContentView: View {
    @ObservedObject var session: ProjectSession

    var body: some View {
        NavigationSplitView {
            sidebar
                .navigationSplitViewColumnWidth(min: 200, ideal: 240)
        } detail: {
            VStack(spacing: 0) {
                tabStrip
                Divider()
                editorArea
                Divider()
                bottomPanel
                    .frame(height: 220)
            }
        }
        .navigationTitle("\(session.project.name) — ClearKrypt IDE")
        .toolbar {
            ToolbarItemGroup {
                Button("Check") { session.runBuild(check: true) }
                    .disabled(session.isBuildRunning)
                Button("Build") { session.runBuild(check: false) }
                    .disabled(session.isBuildRunning)
                Menu("Targets") {
                    Toggle("Swift", isOn: $session.targetSwift)
                    Toggle("Kotlin", isOn: $session.targetKotlin)
                    Toggle("React", isOn: $session.targetReact)
                }
                Button("Save") { session.saveSelectedDocument() }
                    .keyboardShortcut("s")
            }
        }
        .safeAreaInset(edge: .bottom) {
            statusBar
        }
    }

    private var sidebar: some View {
        List {
            ForEach(FileGroup.allCases, id: \.self) { group in
                let files = session.project.files(in: group)
                if !files.isEmpty {
                    Section(group.rawValue) {
                        ForEach(files) { file in
                            Button {
                                session.openFile(file)
                            } label: {
                                HStack {
                                    Text(file.name)
                                    if file.isReadOnly {
                                        Text("generated")
                                            .font(.caption2)
                                            .padding(.horizontal, 4)
                                            .background(.quaternary, in: RoundedRectangle(cornerRadius: 3))
                                    }
                                    Spacer()
                                }
                                .contentShape(Rectangle())
                            }
                            .buttonStyle(.plain)
                        }
                    }
                }
            }
            if !session.outline.isEmpty {
                Section("Outline") {
                    OutlineListView(symbols: session.outline) { symbol in
                        NotificationCenter.default.post(
                            name: .clearkryptNavigate,
                            object: nil,
                            userInfo: [
                                "line": symbol.selectionRange.start.line,
                                "character": symbol.selectionRange.start.character,
                            ])
                    }
                }
            }
        }
    }

    private var tabStrip: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 2) {
                ForEach(session.documents) { document in
                    DocumentTab(session: session, document: document)
                }
            }
            .padding(.horizontal, 6)
            .padding(.vertical, 4)
        }
    }

    @ViewBuilder
    private var editorArea: some View {
        if let document = session.selectedDocument {
            VStack(spacing: 0) {
                if document.file.isReadOnly {
                    Text("Generated by ClearKrypt — read-only. Edit the .ck source instead.")
                        .font(.callout)
                        .frame(maxWidth: .infinity)
                        .padding(6)
                        .background(Color.yellow.opacity(0.2))
                }
                EditorView(session: session, document: document)
            }
            .id(document.id)
        } else {
            VStack(spacing: 8) {
                Text("No file open")
                    .font(.title3)
                    .foregroundStyle(.secondary)
                Text("Double-click a file in the sidebar to start.")
                    .foregroundStyle(.tertiary)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
    }

    private var bottomPanel: some View {
        TabView {
            DiagnosticsPanel(session: session)
                .tabItem { Text("Diagnostics") }
            BuildPanel(session: session)
                .tabItem { Text("Build") }
        }
        .padding(.horizontal, 4)
    }

    private var statusBar: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(session.serverCrashed ? Color.red : (session.serverStatus == "ready" ? Color.green : Color.orange))
                .frame(width: 9, height: 9)
            Text("Language server: \(session.serverStatus)")
                .font(.caption)
            if session.serverCrashed {
                Button("Restart") { session.restartServer() }
                    .font(.caption)
            }
            Spacer()
            Text(session.project.rootPath)
                .font(.caption)
                .foregroundStyle(.secondary)
                .lineLimit(1)
                .truncationMode(.middle)
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 5)
        .background(.bar)
    }
}

private struct DocumentTab: View {
    @ObservedObject var session: ProjectSession
    @ObservedObject var document: OpenDocument

    var body: some View {
        HStack(spacing: 4) {
            Button(document.tabTitle) {
                session.selectedDocumentId = document.id
            }
            .buttonStyle(.plain)
            .fontWeight(session.selectedDocumentId == document.id ? .semibold : .regular)
            Button("✕") {
                session.closeDocument(document)
            }
            .buttonStyle(.plain)
            .font(.caption2)
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 4)
        .background(
            session.selectedDocumentId == document.id ? Color.accentColor.opacity(0.15) : Color.clear,
            in: RoundedRectangle(cornerRadius: 5))
    }
}

private struct OutlineListView: View {
    let symbols: [DocumentSymbol]
    let onSelect: (DocumentSymbol) -> Void

    var body: some View {
        ForEach(flatten(symbols, depth: 0), id: \.id) { entry in
            Button {
                onSelect(entry.symbol)
            } label: {
                HStack {
                    Text(entry.symbol.name)
                        .padding(.leading, CGFloat(entry.depth) * 12)
                    if let detail = entry.symbol.detail {
                        Text(detail)
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                    Spacer()
                }
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
        }
    }

    private struct Entry {
        let id: String
        let symbol: DocumentSymbol
        let depth: Int
    }

    private func flatten(_ symbols: [DocumentSymbol], depth: Int) -> [Entry] {
        var result: [Entry] = []
        for (index, symbol) in symbols.enumerated() {
            result.append(Entry(id: "\(depth)-\(index)-\(symbol.name)", symbol: symbol, depth: depth))
            if let children = symbol.children {
                result.append(contentsOf: flatten(children, depth: depth + 1))
            }
        }
        return result
    }
}

extension Notification.Name {
    /// Posted with userInfo line/character (0-based) to move the editor caret.
    static let clearkryptNavigate = Notification.Name("clearkrypt.navigate")
}
