using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Media;
using Avalonia.Threading;
using Avalonia.VisualTree;
using AvaloniaEdit;
using AvaloniaEdit.CodeCompletion;
using AvaloniaEdit.Document;
using AvaloniaEdit.Editing;
using AvaloniaEdit.Rendering;
using AvaloniaEdit.TextMate;
using ClearKryptIDE.Core.Lsp;
using ClearKryptIDE.Core.Lsp.Protocol;
using ClearKryptIDE.Services;
using ClearKryptIDE.ViewModels;

namespace ClearKryptIDE.Views;

/// <summary>
/// Hosts one AvaloniaEdit editor for an <see cref="EditorDocumentViewModel"/>:
/// TextMate fallback highlighting, language-server semantic tokens layered on
/// top, diagnostic underlines, hover, completion (Ctrl+Space), and the
/// read-only banner for generated files (Constitution Document 7 §10).
/// </summary>
public sealed class EditorHost : ContentControl
{
    private TextEditor? _editor;
    private EditorDocumentViewModel? _document;
    private MainWindowViewModel? _session;
    private TextMate.Installation? _textMate;
    private DiagnosticUnderlineRenderer? _underlineRenderer;
    private SemanticTokenColorizer? _tokenColorizer;
    private DispatcherTimer? _hoverTimer;
    private DispatcherTimer? _tokenRefreshTimer;
    private Point _lastPointerPosition;
    private CompletionWindow? _completionWindow;

    protected override void OnDataContextChanged(EventArgs e)
    {
        base.OnDataContextChanged(e);
        Detach();
        if (DataContext is EditorDocumentViewModel document)
        {
            _document = document;
            Build(document);
        }
    }

    protected override void OnDetachedFromVisualTree(VisualTreeAttachmentEventArgs e)
    {
        base.OnDetachedFromVisualTree(e);
        Detach();
    }

    private void Build(EditorDocumentViewModel document)
    {
        _session = (this.GetVisualRoot() as Window)?.DataContext as MainWindowViewModel;

        _editor = new TextEditor
        {
            Document = document.Document,
            IsReadOnly = document.IsReadOnly,
            ShowLineNumbers = true,
            FontFamily = new FontFamily("Cascadia Code,Consolas,Menlo,DejaVu Sans Mono,monospace"),
            FontSize = 13,
            HorizontalScrollBarVisibility = Avalonia.Controls.Primitives.ScrollBarVisibility.Auto,
        };
        _editor.Options.ConvertTabsToSpaces = true;
        _editor.Options.IndentationSize = 2;

        if (document.IsClearKryptSource)
        {
            var isDark = ActualThemeVariant == Avalonia.Styling.ThemeVariant.Dark;
            _textMate = _editor.InstallTextMate(new ClearKryptRegistryOptions(isDark));
            _textMate.SetGrammar(ClearKryptRegistryOptions.ClearKryptScope);

            _tokenColorizer = new SemanticTokenColorizer(isDark);
            _editor.TextArea.TextView.LineTransformers.Add(_tokenColorizer);

            _underlineRenderer = new DiagnosticUnderlineRenderer(_editor);
            _editor.TextArea.TextView.BackgroundRenderers.Add(_underlineRenderer);

            document.Document.TextChanged += OnTextChanged;
            _editor.TextArea.TextView.PointerMoved += OnPointerMoved;
            _editor.TextArea.TextView.PointerExited += OnPointerExited;
            _editor.KeyDown += OnKeyDown;

            if (_session is not null)
            {
                _session.DocumentDiagnosticsChanged += OnDiagnosticsChanged;
                ApplyDiagnostics();
                _ = RefreshSemanticTokensAsync();
            }
            document.NavigateRequested += OnNavigateRequested;
        }

        if (document.IsReadOnly)
        {
            var banner = new Border
            {
                Background = Brushes.DarkGoldenrod,
                Padding = new Thickness(8, 4),
                Child = new TextBlock
                {
                    Text = "Generated by ClearKrypt — read-only. Edit the .ck source instead.",
                    Foreground = Brushes.White,
                },
            };
            Content = new DockPanel
            {
                Children = { banner, _editor },
            };
            DockPanel.SetDock(banner, Dock.Top);
        }
        else
        {
            Content = _editor;
        }
    }

    private void Detach()
    {
        if (_document is not null)
        {
            _document.Document.TextChanged -= OnTextChanged;
            _document.NavigateRequested -= OnNavigateRequested;
        }
        if (_session is not null)
        {
            _session.DocumentDiagnosticsChanged -= OnDiagnosticsChanged;
        }
        _hoverTimer?.Stop();
        _tokenRefreshTimer?.Stop();
        _textMate?.Dispose();
        _textMate = null;
        _editor = null;
        _document = null;
        _session = null;
        Content = null;
    }

    // -- Change handling ---------------------------------------------------------

    private void OnTextChanged(object? sender, EventArgs e)
    {
        if (_document is null || _session is null)
        {
            return;
        }
        _session.NotifyDocumentChanged(_document);

        _tokenRefreshTimer?.Stop();
        _tokenRefreshTimer ??= new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(700) };
        _tokenRefreshTimer.Tick += OnTokenRefreshTick;
        _tokenRefreshTimer.Start();
    }

    private void OnTokenRefreshTick(object? sender, EventArgs e)
    {
        _tokenRefreshTimer?.Stop();
        if (_tokenRefreshTimer is not null)
        {
            _tokenRefreshTimer.Tick -= OnTokenRefreshTick;
        }
        _ = RefreshSemanticTokensAsync();
    }

    private async Task RefreshSemanticTokensAsync()
    {
        if (_document is null || _session is null || _tokenColorizer is null || _editor is null)
        {
            return;
        }
        if (_session.LanguageServer.State != LanguageServerState.Ready)
        {
            return;
        }
        try
        {
            var tokens = await _session.LanguageServer.SemanticTokensFullAsync(_document.Uri);
            if (tokens is null || _editor is null)
            {
                return;
            }
            var spans = SemanticTokenDecoder.Decode(tokens.Data);
            Dispatcher.UIThread.Post(() =>
            {
                _tokenColorizer.SetTokens(spans);
                _editor?.TextArea.TextView.Redraw();
            });
        }
        catch (Exception)
        {
            // Semantic coloring is progressive enhancement; TextMate stays.
        }
    }

    // -- Diagnostics ---------------------------------------------------------------

    private void OnDiagnosticsChanged(string uri)
    {
        if (_document is not null && uri == _document.Uri)
        {
            Dispatcher.UIThread.Post(ApplyDiagnostics);
        }
    }

    private void ApplyDiagnostics()
    {
        if (_document is null || _session is null || _underlineRenderer is null || _editor is null)
        {
            return;
        }
        _underlineRenderer.SetDiagnostics(_session.DiagnosticsForUri(_document.Uri));
        _editor.TextArea.TextView.Redraw();
    }

    // -- Navigation ------------------------------------------------------------------

    private void OnNavigateRequested(int line, int character)
    {
        if (_editor is null)
        {
            return;
        }
        var targetLine = Math.Clamp(line + 1, 1, _editor.Document.LineCount);
        var docLine = _editor.Document.GetLineByNumber(targetLine);
        var column = Math.Clamp(character + 1, 1, docLine.Length + 1);
        _editor.TextArea.Caret.Line = targetLine;
        _editor.TextArea.Caret.Column = column;
        _editor.ScrollTo(targetLine, column);
        _editor.Focus();
    }

    // -- Hover --------------------------------------------------------------------------

    private void OnPointerMoved(object? sender, PointerEventArgs e)
    {
        if (_editor is null)
        {
            return;
        }
        _lastPointerPosition = e.GetPosition(_editor.TextArea.TextView);
        ToolTip.SetIsOpen(_editor, false);
        _hoverTimer?.Stop();
        _hoverTimer ??= CreateHoverTimer();
        _hoverTimer.Start();
    }

    private void OnPointerExited(object? sender, PointerEventArgs e)
    {
        _hoverTimer?.Stop();
        if (_editor is not null)
        {
            ToolTip.SetIsOpen(_editor, false);
        }
    }

    private DispatcherTimer CreateHoverTimer()
    {
        var timer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(450) };
        timer.Tick += async (_, _) =>
        {
            timer.Stop();
            await ShowHoverAsync();
        };
        return timer;
    }

    private async Task ShowHoverAsync()
    {
        if (_editor is null || _document is null || _session is null ||
            _session.LanguageServer.State != LanguageServerState.Ready)
        {
            return;
        }
        var textView = _editor.TextArea.TextView;
        var position = textView.GetPosition(_lastPointerPosition + textView.ScrollOffset);
        if (position is null)
        {
            return;
        }
        try
        {
            var hover = await _session.LanguageServer.HoverAsync(
                _document.Uri,
                new Position(position.Value.Line - 1, position.Value.Column - 1));
            var text = hover?.Contents?.Value;
            if (string.IsNullOrWhiteSpace(text) || _editor is null)
            {
                return;
            }
            var plain = text.Replace("```ck", string.Empty).Replace("```", string.Empty).Trim();
            Dispatcher.UIThread.Post(() =>
            {
                if (_editor is not null)
                {
                    ToolTip.SetTip(_editor, new TextBlock
                    {
                        Text = plain,
                        FontFamily = new FontFamily("Cascadia Code,Consolas,Menlo,monospace"),
                    });
                    ToolTip.SetIsOpen(_editor, true);
                }
            });
        }
        catch (Exception)
        {
            // Hover is best-effort.
        }
    }

    // -- Completion ------------------------------------------------------------------------

    private void OnKeyDown(object? sender, KeyEventArgs e)
    {
        if (e.Key == Key.Space && e.KeyModifiers.HasFlag(KeyModifiers.Control))
        {
            e.Handled = true;
            _ = ShowCompletionAsync();
        }
    }

    private async Task ShowCompletionAsync()
    {
        if (_editor is null || _document is null || _session is null ||
            _session.LanguageServer.State != LanguageServerState.Ready)
        {
            return;
        }
        var caret = _editor.TextArea.Caret;
        try
        {
            var items = await _session.LanguageServer.CompletionAsync(
                _document.Uri,
                new Position(caret.Line - 1, caret.Column - 1));
            if (items.Count == 0 || _editor is null)
            {
                return;
            }
            Dispatcher.UIThread.Post(() =>
            {
                if (_editor is null)
                {
                    return;
                }
                _completionWindow?.Close();
                _completionWindow = new CompletionWindow(_editor.TextArea);
                foreach (var item in items)
                {
                    _completionWindow.CompletionList.CompletionData.Add(new LspCompletionData(item));
                }
                _completionWindow.Show();
                _completionWindow.Closed += (_, _) => _completionWindow = null;
            });
        }
        catch (Exception)
        {
            // Completion is best-effort.
        }
    }
}

/// <summary>One LSP completion item adapted to AvaloniaEdit's completion list.</summary>
internal sealed class LspCompletionData : ICompletionData
{
    private readonly CompletionItem _item;

    public LspCompletionData(CompletionItem item)
    {
        _item = item;
    }

    public IImage? Image => null;

    public string Text => _item.Label;

    public object Content => _item.Label;

    public object Description => _item.Detail ?? _item.Label;

    public double Priority => 0;

    public void Complete(TextArea textArea, ISegment completionSegment, EventArgs insertionRequestEventArgs)
    {
        textArea.Document.Replace(completionSegment, _item.Label);
    }
}

/// <summary>Colors semantic-token spans over the TextMate baseline.</summary>
internal sealed class SemanticTokenColorizer : DocumentColorizingTransformer
{
    private readonly IReadOnlyDictionary<string, IBrush> _palette;
    private IReadOnlyList<SemanticTokenSpan> _tokens = Array.Empty<SemanticTokenSpan>();

    public SemanticTokenColorizer(bool darkTheme)
    {
        _palette = darkTheme ? DarkPalette : LightPalette;
    }

    public void SetTokens(IReadOnlyList<SemanticTokenSpan> tokens) => _tokens = tokens;

    protected override void ColorizeLine(DocumentLine line)
    {
        if (_tokens.Count == 0)
        {
            return;
        }
        var lineIndex = line.LineNumber - 1;
        foreach (var token in _tokens)
        {
            if (token.Line != lineIndex || !_palette.TryGetValue(token.TokenType, out var brush))
            {
                continue;
            }
            var start = line.Offset + token.StartCharacter;
            var end = Math.Min(start + token.Length, line.EndOffset);
            if (start >= line.Offset && start < end)
            {
                ChangeLinePart(start, end, element => element.TextRunProperties.SetForegroundBrush(brush));
            }
        }
    }

    private static IBrush B(string hex) => new SolidColorBrush(Color.Parse(hex));

    private static readonly IReadOnlyDictionary<string, IBrush> DarkPalette = new Dictionary<string, IBrush>
    {
        ["keyword"] = B("#569cd6"),
        ["string"] = B("#ce9178"),
        ["number"] = B("#b5cea8"),
        ["comment"] = B("#6a9955"),
        ["operator"] = B("#d4d4d4"),
        ["type"] = B("#4ec9b0"),
        ["model"] = B("#4ec9b0"),
        ["enum"] = B("#4ec9b0"),
        ["enumMember"] = B("#9cdcfe"),
        ["errorType"] = B("#f48771"),
        ["function"] = B("#dcdcaa"),
        ["parameter"] = B("#9cdcfe"),
        ["variable"] = B("#9cdcfe"),
        ["property"] = B("#9cdcfe"),
        ["screen"] = B("#4fc1ff"),
        ["component"] = B("#4fc1ff"),
        ["route"] = B("#4fc1ff"),
        ["capability"] = B("#c586c0"),
        ["nativeTarget"] = B("#dcdcaa"),
        ["namespace"] = B("#9cdcfe"),
    };

    private static readonly IReadOnlyDictionary<string, IBrush> LightPalette = new Dictionary<string, IBrush>
    {
        ["keyword"] = B("#0000ff"),
        ["string"] = B("#a31515"),
        ["number"] = B("#098658"),
        ["comment"] = B("#008000"),
        ["operator"] = B("#1f1f1f"),
        ["type"] = B("#267f99"),
        ["model"] = B("#267f99"),
        ["enum"] = B("#267f99"),
        ["enumMember"] = B("#001080"),
        ["errorType"] = B("#cd3131"),
        ["function"] = B("#795e26"),
        ["parameter"] = B("#001080"),
        ["variable"] = B("#001080"),
        ["property"] = B("#001080"),
        ["screen"] = B("#0070c1"),
        ["component"] = B("#0070c1"),
        ["route"] = B("#0070c1"),
        ["capability"] = B("#af00db"),
        ["nativeTarget"] = B("#795e26"),
        ["namespace"] = B("#001080"),
    };
}

/// <summary>Draws dotted underlines beneath diagnostic ranges.</summary>
internal sealed class DiagnosticUnderlineRenderer : IBackgroundRenderer
{
    private static readonly Pen ErrorPen = new(new SolidColorBrush(Color.Parse("#f14c4c")), 1.5, DashStyle.Dot);
    private static readonly Pen WarningPen = new(new SolidColorBrush(Color.Parse("#cca700")), 1.5, DashStyle.Dot);

    private readonly TextEditor _editor;
    private IReadOnlyList<DiagnosticItemViewModel> _diagnostics = Array.Empty<DiagnosticItemViewModel>();

    public DiagnosticUnderlineRenderer(TextEditor editor)
    {
        _editor = editor;
    }

    public KnownLayer Layer => KnownLayer.Selection;

    public void SetDiagnostics(IReadOnlyList<DiagnosticItemViewModel> diagnostics) =>
        _diagnostics = diagnostics;

    public void Draw(TextView textView, DrawingContext drawingContext)
    {
        if (_diagnostics.Count == 0 || !textView.VisualLinesValid)
        {
            return;
        }
        var document = _editor.Document;
        foreach (var diagnostic in _diagnostics)
        {
            if (diagnostic.Line + 1 > document.LineCount)
            {
                continue;
            }
            var line = document.GetLineByNumber(diagnostic.Line + 1);
            var start = Math.Min(line.Offset + diagnostic.Character, line.EndOffset);
            var end = Math.Min(Math.Max(start + 1, line.EndOffset), line.EndOffset);
            if (end <= start)
            {
                end = Math.Min(start + 1, document.TextLength);
            }
            var segment = new TextSegment { StartOffset = start, EndOffset = end };
            var pen = diagnostic.Severity == DiagnosticSeverityLevel.Error ? ErrorPen : WarningPen;
            foreach (var rect in BackgroundGeometryBuilder.GetRectsForSegment(textView, segment))
            {
                var y = rect.Bottom - 1;
                drawingContext.DrawLine(pen, new Point(rect.Left, y), new Point(rect.Right, y));
            }
        }
    }
}
