import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runCli } from 'clearkrypt';

const fixturesRoot = path.resolve(__dirname, '../../../tests/fixtures');

let workDir: string;

beforeEach(() => {
  workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'clearkrypt-cli-'));
});

afterEach(() => {
  fs.rmSync(workDir, { recursive: true, force: true });
});

function copyProject(fixture: string): string {
  const source = path.join(fixturesRoot, 'projects', fixture);
  const target = path.join(workDir, fixture);
  fs.cpSync(source, target, { recursive: true });
  return target;
}

describe('clearkrypt new', () => {
  it('scaffolds a project that immediately checks clean', async () => {
    const created = await runCli(['new', 'my-app'], workDir);
    expect(created.stderr).toBe('');
    expect(created.code).toBe(0);

    const check = await runCli(['check', path.join(workDir, 'my-app')], workDir);
    expect(check.code).toBe(0);
    expect(check.stdout).toContain('No problems found.');
  });

  it('rejects invalid names and existing directories', async () => {
    expect((await runCli(['new', 'Bad_Name'], workDir)).code).toBe(64);
    fs.mkdirSync(path.join(workDir, 'taken'));
    expect((await runCli(['new', 'taken'], workDir)).code).toBe(64);
  });
});

describe('clearkrypt check', () => {
  it('passes on the hello-world fixture', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['check', root], workDir);
    expect(result.code).toBe(0);
  });

  it('reports typed diagnostics with exit code 1 on broken source', async () => {
    const root = copyProject('hello-world');
    fs.writeFileSync(
      path.join(root, 'src', 'main.ck'),
      'module app.main\n\nfn f() -> String {\n  return 42\n}\n',
    );
    const result = await runCli(['check', root], workDir);
    expect(result.code).toBe(1);
    expect(result.stdout).toContain('error[CK0003]');
    expect(result.stdout).toContain('src/main.ck:4:');
  });

  it('emits the documented JSON contract with --json', async () => {
    const root = copyProject('hello-world');
    fs.writeFileSync(
      path.join(root, 'src', 'main.ck'),
      'module app.main\n\nfn f() -> String {\n  return 42\n}\n',
    );
    const result = await runCli(['check', root, '--json'], workDir);
    expect(result.code).toBe(1);
    const parsed = JSON.parse(result.stdout);
    expect(parsed.ok).toBe(false);
    expect(parsed.diagnostics[0]).toMatchObject({
      code: 'CK0003',
      severity: 'error',
      file: 'src/main.ck',
      range: { startLine: 4 },
    });
    expect(parsed.generatedFiles).toEqual([]);
  });

  it('fails with a friendly usage error outside a project', async () => {
    const result = await runCli(['check', workDir], workDir);
    expect(result.code).toBe(64);
    expect(result.stderr).toContain('clearkrypt.toml');
  });
});

describe('clearkrypt build', () => {
  it('emits Swift, Kotlin, and TypeScript for hello-world', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['build', root, '--json'], workDir);
    expect(result.code).toBe(0);

    const parsed = JSON.parse(result.stdout);
    expect(parsed.ok).toBe(true);
    expect(parsed.generatedFiles).toContain('generated/swift/app/main/Greeting.swift');
    expect(parsed.generatedFiles).toContain('generated/kotlin/app/main/Greeting.kt');
    expect(parsed.generatedFiles).toContain('generated/react/app/main.ts');

    const swift = fs.readFileSync(path.join(root, 'generated/swift/app/main/Greeting.swift'), 'utf8');
    expect(swift).toContain('public struct Greeting: Hashable {');
    expect(swift).toContain('Generated by ClearKrypt');
  });

  it('produces byte-identical output across rebuilds', async () => {
    const root = copyProject('hello-world');
    await runCli(['build', root], workDir);
    const first = fs.readFileSync(path.join(root, 'generated/react/app/main.ts'), 'utf8');
    await runCli(['build', root], workDir);
    const second = fs.readFileSync(path.join(root, 'generated/react/app/main.ts'), 'utf8');
    expect(second).toBe(first);
  });

  it('removes stale generated files from previous builds', async () => {
    const root = copyProject('hello-world');
    await runCli(['build', root], workDir);
    const stale = path.join(root, 'generated/swift/stale.swift');
    fs.writeFileSync(stale, '// stale');
    await runCli(['build', root], workDir);
    expect(fs.existsSync(stale)).toBe(false);
  });

  it('fails with CK0005 when a selected target lacks a native implementation', async () => {
    const root = copyProject('hello-world');
    fs.writeFileSync(
      path.join(root, 'src', 'device.ck'),
      `module app.device

native swift fn deviceName() -> String {
  UIDevice.current.name
}
`,
    );
    const result = await runCli(['build', root, '--json'], workDir);
    expect(result.code).toBe(1);
    const parsed = JSON.parse(result.stdout);
    const missing = parsed.diagnostics.filter((d: { code: string }) => d.code === 'CK0005');
    expect(missing.length).toBe(2); // kotlin and react
    expect(parsed.generatedFiles).toEqual([]);
  });

  it('builds the cross-module project', async () => {
    const root = copyProject('two-modules');
    const result = await runCli(['build', root], workDir);
    expect(result.code).toBe(0);
    const kotlin = fs.readFileSync(
      path.join(root, 'generated/kotlin/app/api/Functions.kt'),
      'utf8',
    );
    expect(kotlin).toContain('import app.models.User');
  });
});

describe('language power pack end to end', () => {
  it('builds match, optionals, interpolation, and typed throws for all targets', async () => {
    const root = copyProject('hello-world');
    fs.copyFileSync(
      path.join(fixturesRoot, 'syntax', 'power-pack.ck'),
      path.join(root, 'src', 'main.ck'),
    );
    const result = await runCli(['build', root], workDir);
    expect(result.code).toBe(0);

    const read = (relative: string) => fs.readFileSync(path.join(root, relative), 'utf8');
    expect(read('generated/swift/app/orders/Functions.swift')).toMatchSnapshot();
    expect(read('generated/kotlin/app/orders/Functions.kt')).toMatchSnapshot();
    expect(read('generated/react/app/orders.ts')).toMatchSnapshot();
  });
});

describe('nested (local) functions end to end', () => {
  it('builds capturing and self-recursive local functions for all targets', async () => {
    const root = copyProject('hello-world');
    fs.copyFileSync(
      path.join(fixturesRoot, 'syntax', 'nested-functions.ck'),
      path.join(root, 'src', 'main.ck'),
    );
    const result = await runCli(['build', root], workDir);
    expect(result.code).toBe(0);

    const read = (relative: string) => fs.readFileSync(path.join(root, relative), 'utf8');
    expect(read('generated/swift/app/nested/Functions.swift')).toMatchSnapshot();
    expect(read('generated/kotlin/app/nested/Functions.kt')).toMatchSnapshot();
    expect(read('generated/react/app/nested.ts')).toMatchSnapshot();
  });
});

describe('clearkrypt explain', () => {
  it('shows tokens, AST, IR, and generated code for one file', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['explain', 'src/main.ck', root], workDir);
    expect(result.code).toBe(0);
    expect(result.stdout).toContain('== Tokens: src/main.ck ==');
    expect(result.stdout).toContain('== AST: src/main.ck ==');
    expect(result.stdout).toContain('== Checked IR: src/main.ck (module app.main) ==');
    expect(result.stdout).toContain('== Generated swift: src/main.ck ==');
    expect(result.stdout).toContain('public struct Greeting: Hashable {');
    expect(result.stdout).toContain('== Generated kotlin: src/main.ck ==');
    expect(result.stdout).toContain('data class Greeting(');
    expect(result.stdout).toContain('== Generated react: src/main.ck ==');
    expect(result.stdout).toContain('export interface Greeting {');
  });

  it('narrows to a single stage with --stage', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['explain', 'src/main.ck', root, '--stage', 'ir'], workDir);
    expect(result.code).toBe(0);
    expect(result.stdout).toContain('== Checked IR:');
    expect(result.stdout).not.toContain('== Tokens:');
    expect(result.stdout).not.toContain('== Generated swift:');
  });

  it('rejects an unknown stage name', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['explain', 'src/main.ck', root, '--stage', 'nonsense'], workDir);
    expect(result.code).toBe(64);
    expect(result.stderr).toContain('--stage must be one of');
  });

  it('rejects a file that is not part of the project', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['explain', 'src/nope.ck', root], workDir);
    expect(result.code).toBe(64);
    expect(result.stderr).toContain('is not a .ck file');
  });

  it('shows diagnostics and skips IR/generated code when the project has errors', async () => {
    const root = copyProject('hello-world');
    fs.writeFileSync(
      path.join(root, 'src', 'main.ck'),
      'module app.main\n\nfn f() -> String {\n  return 42\n}\n',
    );
    const result = await runCli(['explain', 'src/main.ck', root, '--stage', 'ir'], workDir);
    expect(result.code).toBe(1);
    expect(result.stdout).toContain('== Checked IR / generated code: skipped ==');
    expect(result.stdout).toContain('error[CK0003]');
  });
});

describe('clearkrypt emit', () => {
  it('emits only the requested target', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['emit', root, '--target', 'swift'], workDir);
    expect(result.code).toBe(0);
    expect(fs.existsSync(path.join(root, 'generated/swift'))).toBe(true);
    expect(fs.existsSync(path.join(root, 'generated/kotlin'))).toBe(false);
  });

  it('requires a --target flag', async () => {
    const root = copyProject('hello-world');
    const result = await runCli(['emit', root], workDir);
    expect(result.code).toBe(64);
  });
});

describe('clearkrypt format', () => {
  it('normalizes whitespace and reports honestly about scope', async () => {
    const root = copyProject('hello-world');
    const file = path.join(root, 'src', 'main.ck');
    fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace('\n\n', '  \n\n'));

    const check = await runCli(['format', root, '--check'], workDir);
    expect(check.code).toBe(1);
    expect(check.stdout).toContain('would format src/main.ck');

    const write = await runCli(['format', root], workDir);
    expect(write.code).toBe(0);
    expect(fs.readFileSync(file, 'utf8')).not.toMatch(/ +\n/);
  });
});

describe('usage', () => {
  it('prints usage without a command and fails', async () => {
    const result = await runCli([], workDir);
    expect(result.code).toBe(64);
    expect(result.stdout).toContain('Usage: clearkrypt');
  });

  it('prints the version', async () => {
    const result = await runCli(['--version'], workDir);
    expect(result.code).toBe(0);
    expect(result.stdout.trim()).toBe('0.1.0');
  });
});
